import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { motion } from "framer-motion";
import { Phone, MapPin, Facebook } from "lucide-react";
import { CONTACT, SITE_NAME, SITE_TAGLINE } from "../../utils/constants";
import { Button } from "../ui/Button";
export const Footer = () => {
    const currentYear = new Date().getFullYear();
    const facebookLink = "https://www.facebook.com/ExtremefitnesscentreMawanella/";
    const mapsLink = "https://share.google/hTNpUpO8KrXqOmyVr";
    return (_jsx("footer", { className: "bg-gradient-to-b from-dark-950 to-dark-900 border-t border-white border-opacity-10 noise-overlay", children: _jsxs("div", { className: "mx-auto max-w-7xl px-4 py-12 sm:px-6 sm:py-16 lg:px-8", children: [_jsxs(motion.div, { className: "mb-10 grid grid-cols-1 gap-10 md:mb-12 md:grid-cols-2 md:gap-12", initial: { opacity: 0, y: 20 }, whileInView: { opacity: 1, y: 0 }, viewport: { once: true }, transition: { duration: 0.5 }, children: [_jsxs("div", { children: [_jsx("h3", { className: "text-xl font-display font-bold gradient-text mb-4", children: SITE_NAME }), _jsx("p", { className: "text-gray-400 text-sm mb-4", children: SITE_TAGLINE }), _jsx("div", { className: "mb-4", children: _jsx(Button, { variant: "primary", size: "sm", onClick: () => {
                                            window.location.href = CONTACT.phoneLink;
                                        }, children: "Call to Join" }) }), _jsxs("div", { className: "flex flex-wrap items-center gap-3", children: [_jsx(motion.a, { href: facebookLink, target: "_blank", rel: "noopener noreferrer", "aria-label": "Extreme Fitness Center Facebook", className: "text-gray-300 hover:text-primary transition-colors", whileHover: { scale: 1.12 }, children: _jsx(Facebook, { size: 22 }) }), _jsx("a", { href: facebookLink, target: "_blank", rel: "noopener noreferrer", className: "text-sm text-gray-300 hover:text-primary transition-colors", children: "Follow us on Facebook" })] })] }), _jsxs("div", { children: [_jsx("h4", { className: "font-semibold mb-4 text-white", children: "Contact & Location" }), _jsxs("div", { className: "space-y-3", children: [_jsxs("a", { href: CONTACT.phoneLink, className: "flex items-center gap-2 text-gray-400 hover:text-primary transition-colors text-sm", children: [_jsx(Phone, { size: 16 }), CONTACT.phone] }), _jsxs("a", { href: CONTACT.secondaryPhoneLink, className: "flex items-center gap-2 text-gray-400 hover:text-primary transition-colors text-sm", children: [_jsx(Phone, { size: 16 }), CONTACT.secondaryPhone] }), _jsxs("div", { className: "flex items-start gap-2 text-gray-400 text-sm", children: [_jsx(MapPin, { size: 16, className: "mt-1 flex-shrink-0" }), _jsxs("div", { children: [_jsx("p", { className: "text-white font-medium", children: "Extreme Fitness Center" }), _jsx("p", { children: CONTACT.addressLine1 }), _jsx("p", { children: CONTACT.addressLine2 })] })] }), _jsx("a", { href: mapsLink, target: "_blank", rel: "noopener noreferrer", className: "inline-flex text-sm text-primary hover:text-accent transition-colors", children: "View location on Google Maps" })] })] })] }), _jsxs(motion.div, { className: "border-t border-white border-opacity-10 pt-8", initial: { opacity: 0 }, whileInView: { opacity: 1 }, viewport: { once: true }, transition: { duration: 0.5, delay: 0.2 }, children: [_jsxs("div", { className: "flex flex-col items-center justify-between gap-4 text-center md:flex-row md:text-left", children: [_jsxs("p", { className: "text-sm text-gray-400", children: ["\u00A9 ", currentYear, " ", SITE_NAME, ". All rights reserved."] }), _jsx("p", { className: "text-gray-500 text-xs", children: "Mawanella, Sri Lanka" })] }), _jsx("div", { className: "flex items-center justify-center mt-6 pt-6 border-t border-white border-opacity-10", children: _jsxs("p", { className: "text-gray-500 text-xs", children: ["Built by", " ", _jsx("a", { href: "https://flowstack.ink/", target: "_blank", rel: "noopener noreferrer", className: "text-primary hover:text-accent transition-colors font-semibold", children: "Flowstack" })] }) })] })] }) }));
};
