import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from "react";
import { motion } from "framer-motion";
import { Menu, X, Sparkles } from "lucide-react";
import { CONTACT, NAV_LINKS, SITE_NAME } from "../../utils/constants";
import { Button } from "../ui/Button";
import logo from "../../../logo.jpg";
export const Navbar = () => {
    const [isOpen, setIsOpen] = useState(false);
    return (_jsx(motion.nav, { className: "fixed top-0 w-full z-50 backdrop-blur-xl bg-dark-950/80 border-b border-white/10", initial: { y: -100 }, animate: { y: 0 }, transition: { duration: 0.5 }, children: _jsxs("div", { className: "max-w-7xl mx-auto px-4 sm:px-6 lg:px-8", children: [_jsxs("div", { className: "flex items-center justify-between h-20", children: [_jsx(motion.div, { className: "flex-shrink-0", whileHover: { scale: 1.05 }, children: _jsxs("a", { href: "#", className: "flex items-center gap-3", children: [_jsx("img", { src: logo, alt: `${SITE_NAME} logo`, className: "h-10 w-10 object-contain rounded-full border border-white/15 ring-soft" }), _jsxs("div", { className: "leading-tight", children: [_jsx("span", { className: "text-xl font-display font-bold gradient-text block", children: SITE_NAME }), _jsx("span", { className: "text-[11px] uppercase tracking-[0.22em] text-gray-400", children: "Performance Studio" })] })] }) }), _jsx("div", { className: "hidden md:flex md:items-center md:gap-8", children: NAV_LINKS.map((link) => (_jsx(motion.a, { href: link.href, className: "text-muted hover:text-primary transition-colors text-sm font-medium tracking-wide", whileHover: { color: "#ff1a1a" }, children: link.label }, link.label))) }), _jsxs("div", { className: "hidden md:flex md:items-center md:gap-3", children: [_jsxs("div", { className: "hidden lg:flex items-center gap-2 rounded-full px-3 py-2 premium-border text-xs text-gray-300", children: [_jsx(Sparkles, { size: 14, className: "text-accent" }), "Elite Coaching"] }), _jsx(Button, { variant: "primary", size: "sm", onClick: () => {
                                        window.location.href = CONTACT.phoneLink;
                                    }, children: "Book a Call" })] }), _jsx("button", { onClick: () => setIsOpen(!isOpen), className: "md:hidden p-2", children: isOpen ? _jsx(X, { size: 24 }) : _jsx(Menu, { size: 24 }) })] }), isOpen && (_jsx(motion.div, { className: "md:hidden pb-4 pt-2", initial: { opacity: 0, y: -20 }, animate: { opacity: 1, y: 0 }, transition: { duration: 0.3 }, children: _jsxs("div", { className: "premium-border rounded-2xl p-4", children: [NAV_LINKS.map((link) => (_jsx("a", { href: link.href, className: "block py-2 text-muted hover:text-primary transition-colors text-sm font-medium", onClick: () => setIsOpen(false), children: link.label }, link.label))), _jsx("div", { className: "pt-4", children: _jsxs(Button, { variant: "primary", size: "sm", className: "w-full", onClick: () => {
                                        window.location.href = CONTACT.phoneLink;
                                    }, children: ["Call ", CONTACT.phone] }) })] }) }))] }) }));
};
