import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { ChevronDown } from "lucide-react";
import { CONTACT, FAQ } from "../../utils/constants";
export const FAQSection = () => {
    const [openIndex, setOpenIndex] = useState(0);
    return (_jsx("section", { id: "faq", className: "section", children: _jsxs("div", { className: "max-w-3xl mx-auto px-4 sm:px-6 lg:px-8", children: [_jsxs(motion.div, { className: "text-center mb-16", initial: { opacity: 0, y: 20 }, whileInView: { opacity: 1, y: 0 }, viewport: { once: true }, transition: { duration: 0.6 }, children: [_jsx("div", { className: "badge-accent mb-4 inline-block", children: "FAQ" }), _jsxs("h2", { className: "section-title", children: ["Common ", _jsx("span", { className: "gradient-text", children: "Questions" })] })] }), _jsx(motion.div, { className: "space-y-4", initial: { opacity: 0 }, whileInView: { opacity: 1 }, viewport: { once: true }, transition: { duration: 0.6 }, children: FAQ.map((faq, index) => (_jsxs(motion.div, { className: "glass rounded-xl overflow-hidden", initial: { opacity: 0, y: 10 }, whileInView: { opacity: 1, y: 0 }, viewport: { once: true }, transition: { delay: index * 0.05 }, children: [_jsxs("button", { onClick: () => setOpenIndex(openIndex === index ? null : index), className: "w-full px-6 py-4 flex items-center justify-between hover:bg-white hover:bg-opacity-5 transition-colors text-left", children: [_jsx("h3", { className: "font-semibold text-white pr-4", children: faq.question }), _jsx(motion.div, { animate: { rotate: openIndex === index ? 180 : 0 }, transition: { duration: 0.3 }, className: "flex-shrink-0", children: _jsx(ChevronDown, { size: 20, className: "text-primary" }) })] }), _jsx(AnimatePresence, { children: openIndex === index && (_jsx(motion.div, { initial: { opacity: 0, height: 0 }, animate: { opacity: 1, height: "auto" }, exit: { opacity: 0, height: 0 }, transition: { duration: 0.3 }, className: "overflow-hidden", children: _jsx("div", { className: "px-6 py-4 border-t border-white border-opacity-10 bg-white bg-opacity-[0.02]", children: _jsx("p", { className: "text-gray-300 leading-relaxed", children: faq.answer }) }) })) })] }, index))) }), _jsxs(motion.div, { className: "mt-12 text-center", initial: { opacity: 0, y: 20 }, whileInView: { opacity: 1, y: 0 }, viewport: { once: true }, transition: { duration: 0.6, delay: 0.3 }, children: [_jsx("p", { className: "text-gray-400 mb-4", children: "Still have questions?" }), _jsxs("a", { href: CONTACT.phoneLink, className: "text-primary hover:text-accent transition-colors font-semibold", children: ["Call ", CONTACT.phone, " \u2192"] })] })] }) }));
};
