import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { ChevronDown, MessageCircle, Phone } from "lucide-react";
import { Button } from "../ui/Button";
import { CONTACT, FAQ } from "../../utils/constants";
import { container, item } from "../../utils/animations";
export const FAQSection = () => {
    const [openIndex, setOpenIndex] = useState(0);
    return (_jsxs("section", { id: "faq", className: "section relative bg-gradient-to-b from-dark-950 via-dark-900 to-dark-950", children: [_jsxs("div", { className: "pointer-events-none absolute inset-0", children: [_jsx("div", { className: "absolute top-20 left-1/4 h-64 w-64 rounded-full bg-accent/8 blur-3xl" }), _jsx("div", { className: "absolute bottom-0 right-1/3 h-80 w-80 rounded-full bg-primary/8 blur-3xl" })] }), _jsxs("div", { className: "max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 relative z-10", children: [_jsxs(motion.div, { className: "mb-12 text-center sm:mb-16", initial: { opacity: 0, y: 20 }, whileInView: { opacity: 1, y: 0 }, viewport: { once: true }, transition: { duration: 0.6 }, children: [_jsx("div", { className: "heading-eyebrow mb-4 inline-block", children: "Common Questions" }), _jsxs("h2", { className: "section-title", children: ["Answers to Your ", _jsx("span", { className: "gradient-text", children: "Top Questions" })] }), _jsx("p", { className: "section-subtitle mx-auto max-w-2xl", children: "Got questions before joining? We've answered the ones we hear most. Still unclear? Reach out\u2014we're happy to help." })] }), _jsx(motion.div, { className: "space-y-3 md:space-y-4", variants: container, initial: "hidden", whileInView: "visible", viewport: { once: true }, children: FAQ.map((faq, index) => (_jsx(motion.div, { variants: item, children: _jsxs(motion.button, { onClick: () => setOpenIndex(openIndex === index ? null : index), className: "group w-full rounded-2xl p-4 text-left transition-all premium-border hover:border-primary/60 md:p-5", whileHover: { backgroundColor: "rgba(255, 0, 0, 0.02)" }, children: [_jsxs("div", { className: "flex items-start justify-between gap-4", children: [_jsx("div", { className: "flex-1", children: _jsx("h3", { className: "text-base font-semibold text-white transition-colors group-hover:text-primary md:text-lg", children: faq.question }) }), _jsx(motion.div, { animate: {
                                                    rotate: openIndex === index ? 180 : 0,
                                                }, transition: { duration: 0.3 }, className: "flex-shrink-0 text-primary mt-1", children: _jsx(ChevronDown, { size: 20 }) })] }), _jsx(AnimatePresence, { children: openIndex === index && (_jsx(motion.div, { initial: { opacity: 0, height: 0 }, animate: { opacity: 1, height: "auto" }, exit: { opacity: 0, height: 0 }, transition: { duration: 0.3 }, className: "overflow-hidden", children: _jsx("p", { className: "mt-4 text-sm leading-relaxed text-gray-300 md:text-base", children: faq.answer }) })) })] }) }, index))) }), _jsxs(motion.div, { className: "mt-16 text-center", initial: { opacity: 0, y: 20 }, whileInView: { opacity: 1, y: 0 }, viewport: { once: true }, transition: { duration: 0.6, delay: 0.2 }, children: [_jsx("p", { className: "text-gray-400 text-base sm:text-lg mb-8 font-medium", children: "Still have questions? Let's talk." }), _jsxs("div", { className: "mx-auto flex max-w-sm flex-col justify-center gap-3 sm:flex-row", children: [_jsxs(Button, { variant: "primary", className: "flex w-full items-center justify-center gap-2 sm:w-auto", onClick: () => {
                                            window.location.href = CONTACT.whatsappLink;
                                        }, children: [_jsx(MessageCircle, { size: 18 }), "WhatsApp Us"] }), _jsxs(Button, { variant: "outline", className: "flex w-full items-center justify-center gap-2 sm:w-auto", onClick: () => {
                                            window.location.href = CONTACT.phoneLink;
                                        }, children: [_jsx(Phone, { size: 18 }), "Call ", CONTACT.phone] })] })] })] })] }));
};
