import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { motion } from "framer-motion";
import { ArrowRight, CheckCircle2, ShieldCheck, Trophy, Zap } from "lucide-react";
import { Button } from "../ui/Button";
import { Badge } from "../ui/Badge";
import { container, item, fadeInUp } from "../../utils/animations";
import { CONTACT } from "../../utils/constants";
export const Hero = () => {
    const proofPoints = [
        "Data-backed programming",
        "Elite coach supervision",
        "Nutrition + training alignment",
    ];
    return (_jsxs("section", { className: "relative min-h-screen pt-32 pb-20 md:pt-40 md:pb-32 overflow-hidden", children: [_jsxs("div", { className: "absolute inset-0 -z-10", children: [_jsx("div", { className: "absolute top-20 right-0 w-96 h-96 bg-primary opacity-20 rounded-full blur-3xl" }), _jsx("div", { className: "absolute bottom-0 left-1/2 w-96 h-96 bg-accent opacity-10 rounded-full blur-3xl" })] }), _jsx("div", { className: "max-w-7xl mx-auto px-4 sm:px-6 lg:px-8", children: _jsxs(motion.div, { className: "grid lg:grid-cols-2 gap-12 lg:gap-16 items-center", variants: container, initial: "hidden", animate: "visible", children: [_jsxs("div", { children: [_jsx(motion.div, { variants: item, className: "mb-6", children: _jsx(Badge, { variant: "accent", className: "tracking-wide uppercase", children: "Premium Fitness Brand Experience" }) }), _jsxs(motion.h1, { variants: fadeInUp, className: "text-5xl md:text-7xl font-display font-bold mb-6 leading-[1.04] text-balance", children: ["Transform Your Body With", " ", _jsx("span", { className: "gradient-text", children: "Elite-Level" }), " Coaching"] }), _jsx(motion.p, { variants: fadeInUp, className: "text-lg md:text-xl text-gray-300 max-w-2xl mb-8 text-balance", children: "A high-performance training environment designed for serious results. We combine coaching, nutrition, and accountability to deliver measurable progress." }), _jsxs(motion.div, { variants: fadeInUp, className: "flex flex-col sm:flex-row gap-4 items-start mb-10", children: [_jsxs(Button, { variant: "primary", size: "lg", className: "group", onClick: () => document
                                                .getElementById("services")
                                                ?.scrollIntoView({ behavior: "smooth" }), children: ["Explore Programs", _jsx(ArrowRight, { className: "group-hover:translate-x-2 transition-transform", size: 20 })] }), _jsxs(Button, { variant: "outline", size: "lg", onClick: () => {
                                                window.location.href = CONTACT.phoneLink;
                                            }, children: ["Call ", CONTACT.phone] })] }), _jsx(motion.div, { variants: fadeInUp, className: "space-y-3", children: proofPoints.map((point) => (_jsxs("div", { className: "flex items-center gap-3 text-gray-200 text-sm md:text-base", children: [_jsx(CheckCircle2, { className: "text-accent", size: 18 }), point] }, point))) })] }), _jsx(motion.div, { variants: fadeInUp, children: _jsxs("div", { className: "relative aspect-[4/5] rounded-3xl overflow-hidden premium-border", children: [_jsx("img", { src: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=1200&h=600&fit=crop", alt: "Extreme Fitness Center training space", className: "w-full h-full object-cover" }), _jsx("div", { className: "absolute inset-0 bg-gradient-to-t from-dark-950 via-dark-950 via-opacity-30 to-transparent" }), _jsxs("div", { className: "absolute top-5 left-5 right-5 premium-border rounded-2xl px-4 py-3 flex items-center justify-between", children: [_jsxs("div", { className: "flex items-center gap-2 text-white font-semibold text-sm", children: [_jsx(ShieldCheck, { size: 16, className: "text-accent" }), "Trusted Results Framework"] }), _jsx("div", { className: "text-xs text-gray-300", children: "Since Day One" })] }), _jsxs("div", { className: "absolute bottom-5 left-5 right-5 grid grid-cols-3 gap-3", children: [_jsxs("div", { className: "premium-border rounded-xl p-3", children: [_jsx(Trophy, { size: 16, className: "text-primary mb-2" }), _jsx("div", { className: "text-xl font-bold text-white", children: "7+" }), _jsx("p", { className: "text-xs text-gray-300", children: "Elite Programs" })] }), _jsxs("div", { className: "premium-border rounded-xl p-3", children: [_jsx(Zap, { size: 16, className: "text-primary mb-2" }), _jsx("div", { className: "text-xl font-bold text-white", children: "1:1" }), _jsx("p", { className: "text-xs text-gray-300", children: "Focused Coaching" })] }), _jsxs("div", { className: "premium-border rounded-xl p-3", children: [_jsx(CheckCircle2, { size: 16, className: "text-primary mb-2" }), _jsx("div", { className: "text-xl font-bold text-white", children: "All" }), _jsx("p", { className: "text-xs text-gray-300", children: "Fitness Levels" })] })] })] }) })] }) })] }));
};
