import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { ChevronLeft, ChevronRight, Star } from "lucide-react";
import { TESTIMONIALS } from "../../utils/constants";
export const Testimonials = () => {
    const [current, setCurrent] = useState(0);
    const next = () => setCurrent((prev) => (prev + 1) % TESTIMONIALS.length);
    const prev = () => setCurrent((prev) => (prev - 1 + TESTIMONIALS.length) % TESTIMONIALS.length);
    const testimonial = TESTIMONIALS[current];
    return (_jsx("section", { id: "testimonials", className: "section bg-gradient-to-b from-dark-950 via-dark-900 to-dark-950", children: _jsxs("div", { className: "max-w-4xl mx-auto px-4 sm:px-6 lg:px-8", children: [_jsxs(motion.div, { className: "text-center mb-16", initial: { opacity: 0, y: 20 }, whileInView: { opacity: 1, y: 0 }, viewport: { once: true }, transition: { duration: 0.6 }, children: [_jsx("div", { className: "badge-accent mb-4 inline-block", children: "Testimonials" }), _jsxs("h2", { className: "section-title", children: ["Hear From Our ", _jsx("span", { className: "gradient-text", children: "Members" })] })] }), _jsxs(motion.div, { className: "glass rounded-2xl p-8 md:p-12 min-h-96 flex flex-col justify-center", initial: { opacity: 0, scale: 0.9 }, whileInView: { opacity: 1, scale: 1 }, viewport: { once: true }, transition: { duration: 0.5 }, children: [_jsx(AnimatePresence, { mode: "wait", children: _jsxs(motion.div, { initial: { opacity: 0, y: 20 }, animate: { opacity: 1, y: 0 }, exit: { opacity: 0, y: -20 }, transition: { duration: 0.3 }, className: "text-center", children: [_jsx("div", { className: "flex justify-center gap-1 mb-6", children: [...Array(testimonial.rating)].map((_, i) => (_jsx(Star, { size: 20, className: "fill-accent text-accent" }, i))) }), _jsxs("blockquote", { className: "text-2xl md:text-3xl font-display text-white mb-8 leading-relaxed text-balance", children: ["\"", testimonial.content, "\""] }), _jsxs("div", { className: "flex items-center justify-center gap-4", children: [_jsx("img", { src: testimonial.image, alt: testimonial.name, className: "w-16 h-16 rounded-full object-cover border-2 border-primary" }), _jsxs("div", { className: "text-left", children: [_jsx("p", { className: "font-semibold text-white", children: testimonial.name }), _jsx("p", { className: "text-gray-400 text-sm", children: testimonial.role })] })] })] }, current) }), _jsxs("div", { className: "flex items-center justify-between mt-12 pt-8 border-t border-white border-opacity-10", children: [_jsx("div", { className: "flex gap-2", children: TESTIMONIALS.map((_, index) => (_jsx(motion.button, { onClick: () => setCurrent(index), className: `h-2 rounded-full transition-all ${index === current ? "bg-primary w-8" : "bg-gray-600 w-2"}`, whileHover: { scale: 1.2 } }, index))) }), _jsxs("div", { className: "flex gap-3", children: [_jsx(motion.button, { onClick: prev, className: "w-10 h-10 rounded-full glass flex items-center justify-center hover:border-primary transition-colors", whileHover: { scale: 1.1 }, whileTap: { scale: 0.95 }, children: _jsx(ChevronLeft, { size: 20 }) }), _jsx(motion.button, { onClick: next, className: "w-10 h-10 rounded-full glass flex items-center justify-center hover:border-primary transition-colors", whileHover: { scale: 1.1 }, whileTap: { scale: 0.95 }, children: _jsx(ChevronRight, { size: 20 }) })] })] })] })] }) }));
};
